# Generated by Django 5.0 on 2024-03-09 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0002_contact'),
    ]

    operations = [
        migrations.CreateModel(
            name='Horoscope',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('birth_day', models.IntegerField()),
                ('birth_month', models.IntegerField()),
                ('birth_year', models.IntegerField()),
                ('prediction', models.TextField()),
            ],
        ),
    ]
