# Generated by Django 5.0 on 2024-03-09 21:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0003_horoscope'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Horoscope',
            new_name='dailyhoroscopes',
        ),
    ]
