# Generated by Django 5.0 on 2024-03-09 21:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0005_alter_dailyhoroscopes_birth_month'),
    ]

    operations = [
        migrations.DeleteModel(
            name='dailyhoroscopes',
        ),
    ]
